// frontend/scripts/pages/ingredientMatcher.js
// Purpose: Wires up the "Cook With What You Have" section on the homepage.
// Sends the user's ingredient list to the backend's scoring endpoint and
// renders the ranked results using the same card component as everywhere
// else on the site (renderRecipeCard detects match fields automatically).

document.getElementById('matcherBtn')?.addEventListener('click', runIngredientMatch);
document.getElementById('matcherInput')?.addEventListener('keypress', (e) => {
  if (e.key === 'Enter') runIngredientMatch();
});
document.getElementById('aiSuggestBtn')?.addEventListener('click', runAiSuggestion);

async function runIngredientMatch() {
  const input = document.getElementById('matcherInput');
  const grid = document.getElementById('matcherGrid');
  const emptyMsg = document.getElementById('matcherEmptyMsg');
  const aiRow = document.getElementById('aiSuggestRow');
  const aiResult = document.getElementById('aiSuggestResult');
  const ingredients = input.value.trim();

  if (!ingredients) {
    showToast('Type at least one ingredient first');
    return;
  }

  emptyMsg.style.display = 'none';
  aiRow.style.display = 'none';
  aiResult.innerHTML = '';
  renderSkeletons('matcherGrid', 4);

  try {
    const results = await matchByIngredients(ingredients, 8);
    if (results.length === 0) {
      grid.innerHTML = '';
      emptyMsg.style.display = 'block';
    } else {
      renderCardGrid(results, 'matcherGrid');
    }
    // Offer the AI fallback after every search, whether matches were
    // found or not — sometimes a fresh idea beats browsing the list.
    aiRow.style.display = 'block';
  } catch (err) {
    console.error('Ingredient match failed:', err);
    grid.innerHTML = '';
    emptyMsg.textContent = 'Something went wrong — please try again in a moment.';
    emptyMsg.style.display = 'block';
    showToast('Could not fetch matches right now');
  }
}

async function runAiSuggestion() {
  const input = document.getElementById('matcherInput');
  const aiResult = document.getElementById('aiSuggestResult');
  const aiBtn = document.getElementById('aiSuggestBtn');
  const ingredients = input.value.trim();
  if (!ingredients) return;

  aiBtn.disabled = true;
  aiBtn.textContent = 'Thinking…';
  aiResult.innerHTML = '';

  try {
    const data = await fetchAiSuggestion(ingredients);

    if (!data.available) {
      aiResult.innerHTML = `<p class="matcher-hint">AI suggestions aren't available right now — try the matches above instead.</p>`;
      return;
    }

    const r = data.recipe;
    aiResult.innerHTML = `
      <div class="ai-suggest-card">
        <span class="ai-suggest-tag">✨ AI-GENERATED IDEA — not from our recipe database</span>
        <h3>${r.name}</h3>
        <p class="ai-meta"><i class="bi bi-clock"></i> ${r.minutes} min</p>
        <strong>Ingredients</strong>
        <ul>${r.ingredients.map((i) => `<li>${i}</li>`).join('')}</ul>
        <strong>Steps</strong>
        <ol>${r.steps.map((s) => `<li>${s}</li>`).join('')}</ol>
        <p class="ai-suggest-disclaimer">Generated by AI — double-check quantities and cook times before relying on it.</p>
      </div>
    `;
  } catch (err) {
    console.error('AI suggestion failed:', err);
    aiResult.innerHTML = `<p class="matcher-hint">Couldn't reach the AI service right now — please try again shortly.</p>`;
  } finally {
    aiBtn.disabled = false;
    aiBtn.textContent = '✨ Ask AI for a recipe idea instead';
  }
}